export default function Loading({ text }) {
  const list = [
    'Reticulating splines...',
    'Generating witty dialog...',
    'Swapping time and space...',
    'Spinning violently around the y-axis...',
    'Tokenizing real life...',
    'Bending the spoon...',
    'Filtering morale...',
    'Proving P=NP...',
    'Entangling superstrings...',
    'Twiddling thumbs...',
    'Searching for plot device...',
    'Trying to sort in O(n)...',
    'Laughing at your pictures-i mean, loading...',
    'Sending data to NS-i mean, our servers.',
    'Looking for sense of humour, please hold on.',
    'Please wait while the intern refills his coffee.',
    'A different error message? Finally, some progress!',
    'Hold on while we wrap up our git together...sorry',
    'Please hold on as we reheat our coffee',
    'Kindly hold on as we convert this bug to a feature...',
    'Kindly hold on as our intern quits vim...',
    'Winter is coming...',
    'Installing dependencies',
    'Switching to the latest JS framework...',
    'Distracted by cat gifs',
    'Finding someone to hold my beer',
    'BRB, working on my side project',
    '@todo Insert witty loading message',
    "Let's hope it's worth the wait",
    'Aw, snap! Not..',
    'Ordering 1s and 0s...',
    'Updating dependencies...',
    "Whatever you do, don't look behind you...",
    'Please wait... Consulting the manual...',
    "It is dark. You're likely to be eaten by a grue.",
    'Loading funny message...',
    "It's 10:00pm. Do you know where your children are?",
    'Waiting Daenerys say all her titles...',
    'Feel free to spin in your chair',
    'What the what?',
    'format C: ...',
    'Forget you saw that password I just typed into the IM ...',
    "What's under there?",
    'Your computer has a virus, its name is Windows!',
    'Go ahead, hold your breath and do an ironman plank till loading complete',
    'Bored of slow loading spinner, buy more RAM!',
    "Help, I'm trapped in a loader!",
    'What is the difference btwn a hippo and a zippo? One is really heavy, the other is a little lighter',
    'Please wait, while we purge the Decepticons for you. Yes, You can thanks us later!',
    "Chuck Norris once urinated in a semi truck's gas tank as a joke....that truck is now known as Optimus Prime.",
    'Chuck Norris doesn’t wear a watch. HE decides what time it is.',
    'Mining some bitcoins...',
    'Downloading more RAM..',
    'Updating to Windows Vista...',
    'Deleting System32 folder',
    "Hiding all ;'s in your code",
    'Alt-F4 speeds things up.',
    'Initializing the initializer...',
    'When was the last time you dusted around here?',
    'Optimizing the optimizer...',
    'Last call for the data bus! All aboard!',
    'Running swag sticker detection...',
    "Never let a computer know you're in a hurry.",
    'A computer will do what you tell it to do, but that may be much different from what you had in mind.',
    "Some things man was never meant to know. For everything else, there's Google.",
    "Unix is user-friendly. It's just very selective about who its friends are.",
    'Shovelling coal into the server',
    'Pushing pixels...',
    'How about this weather, eh?',
    'Building a wall...',
    'Everything in this universe is either a potato or not a potato',
    'The severity of your issue is always lower than you expected.',
    'Updating Updater...',
    'Downloading Downloader...',
    'Debugging Debugger...',
    'Reading Terms and Conditions for you.',
    'Digested cookies being baked again.',
    'Live long and prosper.',
    "There is no cow level, but there's a goat one!",
    'Deleting all your hidden porn...',
    'Running with scissors...',
    'Definitely not a virus...',
    'You may call me Steve.',
    'You seem like a nice person...',
    "Coffee at my place, tommorow at 10A.M. - don't be late!",
    'Work, work...',
    'Patience! This is difficult, you know...',
    'Discovering new ways of making you wait...',
    'Your time is very important to us. Please wait while we ignore you...',
    'Time flies like an arrow; fruit flies like a banana',
    'Two men walked into a bar; the third ducked...',
    'Sooooo... Have you seen my vacation photos yet?',
    "Sorry we are busy catching em' all, we're done soon",
    'TODO: Insert elevator music',
    'Still faster than Windows update',
    'Composer hack: Waiting for reqs to be fetched is less frustrating if you add -vvv to your command.',
    'Please wait while the minions do their work',
    'Grabbing extra minions',
    'Doing the heavy lifting',
    "We're working very Hard .... Really",
    'Waking up the minions',
    'You are number 2843684714 in the queue',
    'Please wait while we serve other customers...',
    'Our premium plan is faster',
    'Feeding unicorns...',
    'Rupturing the subspace barrier',
    'Creating an anti-time reaction',
    'Converging tachyon pulses',
    'Bypassing control of the matter-antimatter integrator',
    'Adjusting the dilithium crystal converter assembly',
    'Reversing the shield polarity',
    'Disrupting warp fields with an inverse graviton burst',
    'Up, Up, Down, Down, Left, Right, Left, Right, B, A.',
    'Do you like my loading animation? I made it myself',
    'Whoah, look at it go!',
    "No, I'm awake. I was just resting my eyes.",
    'One mississippi, two mississippi...',
    "Don't panic... AHHHHH!",
    'Ensuring Gnomes are still short.',
    'Baking ice cream...',
  ];
  if (!text) text = list.sort(() => 0.5 - Math.random())[0];
  return (
    <>
      <div className='grid h-20 card glass rounded-md place-items-center text-3xl'>
        {text}
      </div>
    </>
  );
}
